/* =========================================================
   DATA — 브로슈어(Connect_2026_브로슈어_수정_0921.pdf) 기준
   p.11–13 일정 / p.14–30 기업 브로슈어
   type: ops(운영) · session(세션) · network(네트워킹 피크) · key(CONNECT 핵심)
   ========================================================= */
window.SCHEDULE = {
  "2026-10-08": {
    label: "8 October",
    ko: "10월 8일 (목)",
    slots: [
      { start: "07:30", end: "09:00", type: "ops",
        title: "Exhibition Set-up & Startup Counter Preparation",
        ko: "전시 설치 및 스타트업 카운터 준비 — Congress Pass 수령, 기업별 홍보물·디스플레이·브로슈어 세팅 및 최종 현장 브리핑",
        recs: ["09:00까지 전시 준비 완료 권장"] },
      { start: "09:30", end: "11:00", type: "session",
        title: "Opening Ceremony & Plenary 1 — Better, Not More: Why the Future of Healthcare is Fewer Patients",
        ko: "개막식 및 Plenary 1 — 더 많이가 아닌, 더 나은 의료",
        recs: ["참여기업 참석 권장", "SHBC 및 싱가포르 연구·혁신·과학·임상 생태계 이해"] },
      { start: "11:00", end: "11:30", type: "network",
        title: "Tea Break · Startup Showcase & Attendee Engagement (Peak Hour)",
        ko: "티브레이크 제공 · 스타트업 쇼케이스 및 참가자 교류 (집중 네트워킹)",
        recs: ["SHBC 참가자 및 잠재 파트너와 집중 네트워킹 권장"] },
      { start: "11:30", end: "13:00", type: "ops",
        title: "Startup Showcase & Business Networking (Off Peak)",
        ko: "스타트업 쇼케이스 및 비즈니스 네트워킹 (비집중 시간)",
        recs: ["필요 기업 대상 AV 체크 및 리허설 예정"],
        parallel: [
          { title: "Track 1A: Adding Years to Life – Why Value-Based Care Matters", ko: "건강수명 연장 — 가치 기반 의료가 중요한 이유", rec: "관심 분야에 따라 선택 참석" },
          { title: "Track 1B: AI in Clinical Care in 2026: Friend or Foe", ko: "2026년 임상현장의 AI: 친구인가, 적인가", rec: "AI·디지털헬스 기업 참석 권장" },
          { title: "Track 1C: A Responsible Future: Navigating the Ethics of Predictive and Preventive Medicine", ko: "책임 있는 미래: 예측·예방의학의 윤리적 과제", rec: "예방·예측의료 관련 기업 선택 참석" },
        ] },
      { start: "13:00", end: "14:30", type: "network",
        title: "Lunch · Startup Showcase & Attendee Engagement (Peak Hour)",
        ko: "중식 제공 · 스타트업 쇼케이스 및 참가자 교류 (집중 네트워킹)",
        recs: ["참가자 및 파트너와 적극적인 네트워킹 권장"] },
      { start: "14:30", end: "16:00", type: "key", pitch: true,
        title: "CONNECT 2026 · Pitchstop — Dedicated Startup Pitching Session",
        ko: "스타트업 전용 피칭 세션 · 기업별 5분 발표 + 5분 Q&A",
        recs: ["Judging panel 및 헬스케어 혁신 관계자 대상 기업 소개", "전문가 피드백·투자·PoC·사업협력 기회 발굴"] },
      { start: "16:00", end: "16:30", type: "network",
        title: "Tea Break · Startup Showcase & Attendee Engagement (Peak Hour)",
        ko: "티브레이크 제공 · 스타트업 쇼케이스 및 참가자 교류",
        recs: ["Pitchstop 관심 파트너 대상 후속 네트워킹 권장"] },
      { start: "16:30", end: "18:00", type: "session",
        title: "Track 2A: Innovation for Healthy Longevity – From Bench to Clinic (Hall 1)",
        ko: "건강한 장수를 위한 혁신 — 연구실에서 임상으로 (Hall 1)",
        recs: ["CMTi-supported session", "기초연구 → 임상혁신 전환과정 이해", "임상·산업 협력 가능성 발굴"] },
    ],
  },
  "2026-10-09": {
    label: "9 October",
    ko: "10월 9일 (금)",
    slots: [
      { start: "08:30", end: "08:45", type: "ops",
        title: "Booth Readiness Check — No re-setup required",
        ko: "부스 준비상태 확인 — 별도 재설치 불필요",
        recs: ["전시 시작 전 기업별 카운터 최종 점검"] },
      { start: "08:45", end: "10:30", type: "ops",
        title: "Startup Showcase & Business Networking (Off Peak)",
        ko: "스타트업 쇼케이스 및 비즈니스 네트워킹 (비집중 시간)",
        recs: ["자유 비즈니스 네트워킹 및 전시 운영"],
        parallel: [
          { title: "Plenary 3: Singapore's National Precision Medicine Programme", ko: "싱가포르 국가 정밀의료 프로그램 — 유전체 연구를 산업적 성과로", rec: "Precision Medicine·Genomics 기업 참석 권장" },
          { title: "Panel: Singapore's Precision Medicine Journey – From Genomic Discovery to Healthcare Impact", ko: "싱가포르 정밀의료의 여정", rec: "임상 적용 및 사업화 관점 참고" },
        ] },
      { start: "10:30", end: "11:00", type: "network",
        title: "Tea Break · Startup Showcase & Attendee Engagement (Peak Hour)",
        ko: "티브레이크 제공 · 집중 네트워킹",
        recs: ["참가자 및 잠재 파트너와 집중 네트워킹 권장"] },
      { start: "11:00", end: "12:30", type: "ops",
        title: "Startup Showcase & Business Networking (Off Peak)",
        ko: "스타트업 쇼케이스 및 비즈니스 네트워킹 (비집중 시간)",
        recs: ["자유 네트워킹 및 프로그램 선택 참석"],
        parallel: [
          { title: "3A Precision Medicine in Shaping the Future of Healthcare Delivery in Singapore", ko: "싱가포르 의료서비스의 미래를 이끄는 정밀의료", rec: "정밀의료 관련 기업 참석 권장" },
          { title: "3B Frontiers in Muscle Health", ko: "근육 건강의 새로운 프런티어", rec: "근골격·재활 관련 기업 선택 참석" },
          { title: "3C All Hands on Deck: Building a Generalist Palliative Care Ecosystem", ko: "모두가 함께 만드는 일반 완화의료 생태계", rec: "관련 기업 선택 참석" },
        ] },
      { start: "12:30", end: "14:00", type: "network",
        title: "Lunch · Startup Showcase & Attendee Engagement (Peak Hour)",
        ko: "중식 제공 · 집중 네트워킹",
        recs: ["기존 미팅 상대 및 신규 파트너와 후속 논의 권장"] },
      { start: "14:00", end: "15:30", type: "ops",
        title: "Startup Showcase & Business Networking (Off Peak)",
        ko: "스타트업 쇼케이스 및 비즈니스 네트워킹 (비집중 시간)",
        recs: ["자유 비즈니스 네트워킹 및 전시 운영"],
        parallel: [
          { title: "Plenary 4: A Social Norms Approach to Healthy Living — Prof. Rajiv N. Rimal", ko: "건강한 삶을 위한 사회규범 접근법", rec: "예방·건강증진 관련 기업 참고" },
        ] },
      { start: "15:30", end: "16:00", type: "network",
        title: "Tea Break · Startup Showcase & Attendee Engagement (Final Peak)",
        ko: "티브레이크 제공 · 마지막 집중 네트워킹",
        recs: ["주요 파트너 대상 최종 네트워킹 및 후속 논의 권장"] },
      { start: "16:00", end: "17:30", type: "ops",
        title: "Close & Counter Wrap-up — counters close by 17:00",
        ko: "마감 및 카운터 정리 — 17:00까지 스타트업 카운터 운영 종료",
        recs: ["주요 파트너 대상 최종 follow-up 권장"],
        parallel: [
          { title: "4A Digital Health: Bridging the Tech Divide", ko: "디지털 헬스 — 기술 격차를 연결하다", rec: "Digital Health 기업 참석 권장" },
          { title: "4B Extending Healthspan by Design: Clinical 3D Printing across the Care Continuum", ko: "의료 전주기의 임상 3D 프린팅", rec: "MedTech·3D Printing 기업 선택 참석" },
          { title: "4C Golden Resilience — Supporting Elderly Patients in Their Cancer Journey", ko: "고령 암환자의 치료 여정 지원", rec: "Oncology·Healthy Aging 기업 선택 참석" },
        ] },
    ],
  },
};

/* 기업 브로슈어 — null 값은 "업데이트 예정"으로 표시됩니다.
   관리 시트 A열(로그인 ID)이 id 또는 aliases 중 하나와 같으면 이 기업으로 인식합니다. (대소문자 무관) */
window.COMPANIES = [
  { id: "speechnrt", aliases: ["speech", "speech nrt"], no: 1, pitch: "14:30",
    name: "Speech NRT Co.", legal: "MalGwaHakNoRiTeo Co.", tagline: null,
    summary: "AI-powered personalized speech rehabilitation platform combining speech analysis, pronunciation training, and digital therapeutics.",
    tags: ["Digital Health", "DTx", "AI"],
    rep: null, founded: null, location: null,
    core: null, achievements: null, expansion: null,
    website: null, email: null, contactPerson: null },
  { id: "lifefuturetech", aliases: [], no: 2, pitch: "14:40",
    name: "Lifefuturetech", legal: null, tagline: null,
    summary: "AI-powered healthcare platform delivering personalized health monitoring, clinical communication, and end-to-end medical support through Med-LLM technology.",
    tags: ["Digital Health", "Med-LLM"],
    rep: null, founded: null, location: null,
    core: null, achievements: null, expansion: null,
    website: null, email: null, contactPerson: null },
  { id: "cdthera", aliases: ["cd thera"], no: 3, pitch: "14:50",
    name: "CD Thera", legal: null, tagline: "Early Detection, Better Prevention",
    summary: "A non-invasive oral-saliva multi-biomarker + AI platform (PDX-AD) for early, at-home dementia risk screening and longitudinal brain-health monitoring.",
    tags: ["Diagnostics", "Dementia", "AI"],
    rep: null, founded: null, location: null,
    core: "A non-invasive oral-saliva multi-biomarker + AI platform (PDX-AD) for early, at-home dementia risk screening and longitudinal brain-health monitoring.",
    achievements: null, expansion: null,
    website: null, email: null, contactPerson: null },
  { id: "careminder", aliases: [], no: 4, pitch: "15:00",
    name: "CareMinder Co., Ltd.", legal: null, tagline: null,
    summary: "Voice AI for smarter hospitals, automating nursing handovers, clinical documentation, and patient-to-care-team communication.",
    tags: ["Hospital AI", "Voice AI"],
    rep: null, founded: null, location: null,
    core: null, achievements: null, expansion: null,
    website: null, email: null, contactPerson: null },
  { id: "jeongjin", aliases: ["jeongjin bioscience"], no: 5, pitch: "15:10",
    name: "JEONGJIN BIOSCIENCE Co., Ltd.", legal: null, tagline: null,
    summary: "Developing next-generation secretome-based, cell-free therapeutics for regenerative medicine, inflammatory diseases, and cancer.",
    tags: ["Therapeutics", "Regenerative"],
    rep: null, founded: null, location: null,
    core: "Developing next-generation secretome-based, cell-free therapeutics for regenerative medicine, inflammatory diseases, and cancer.",
    achievements: null, expansion: null,
    website: null, email: null, contactPerson: null },
  { id: "beyondmedicine", aliases: ["beyond", "beyond medicine"], no: 6, pitch: "15:20",
    name: "Beyondmedicine", legal: null, tagline: null,
    summary: "Developing evidence-based prescription digital therapeutics for temporomandibular disorders, combining guided therapy with clinician-connected digital care.",
    tags: ["DTx", "TMD"],
    rep: null, founded: null, location: null,
    core: "Developing evidence-based prescription digital therapeutics for temporomandibular disorders, combining guided therapy with clinician-connected digital care.",
    achievements: null, expansion: null,
    website: null, email: null, contactPerson: null },
  { id: "inexoplat", aliases: [], no: 7, pitch: "15:30",
    name: "INEXOPLAT Inc.", legal: null, tagline: null,
    summary: "Developing next-generation exosome-based therapeutics targeting refractory solid tumors through immune-based precision oncology.",
    tags: ["Oncology", "Exosome"],
    rep: null, founded: null, location: null,
    core: "Developing next-generation exosome-based therapeutics targeting refractory solid tumors through immune-based precision oncology.",
    achievements: null, expansion: null,
    website: null, email: null, contactPerson: null },
  { id: "imitarscience", aliases: ["imitar", "imita", "imita science"], no: 8, pitch: "15:40",
    name: "IMITARSCIENCE", legal: null, tagline: null,
    summary: "Advancing human-relevant drug development through multi-organ-on-a-chip platforms for efficacy, toxicity, and non-clinical assessment.",
    tags: ["Organ-on-a-chip", "Non-clinical"],
    rep: null, founded: null, location: null,
    core: "Advancing human-relevant drug development through multi-organ-on-a-chip platforms for efficacy, toxicity, and non-clinical assessment.",
    achievements: null, expansion: null,
    website: null, email: null, contactPerson: null },
];
