/* =========================================================
   DATA — 브로슈어(CONNECT_2026_브로슈어_최종_1.pdf) 기준
   p.21–22 일정 / p.32–43 기업 브로슈어 (CDThera ~ IMITAR)
   type: ops(운영) · session(세션) · network(네트워킹 피크) · key(CONNECT 핵심)
   ========================================================= */
window.SCHEDULE = {
  "2026-10-08": {
    label: "8 October",
    ko: "10월 8일 (목)",
    slots: [
      { start: "07:30", end: "09:00", type: "ops",
        title: "Exhibition Set-up & Startup Counter Preparation",
        ko: "전시 설치 및 스타트업 카운터 준비 – Congress Pass 수령, 기업별 홍보물·디스플레이·브로슈어 세팅 및 최종 현장 브리핑 진행",
        recs: ["09:00까지 전시 준비 완료 권장"] },
      { start: "09:30", end: "11:00", type: "session",
        title: "Opening Ceremony & Plenary 1 – Better, Not More: Why the Future of Healthcare is Fewer Patients",
        ko: "개막식 및 Plenary 1 – 더 많이가 아닌, 더 나은 의료: 왜 미래의 헬스케어는 더 적은 환자를 지향하는가",
        recs: ["참여기업 참석 권장", "SHBC 및 싱가포르 연구·혁신·과학·임상 생태계 이해"] },
      { start: "11:00", end: "11:30", type: "network",
        title: "Tea Break (provided) · Startup Showcase & Attendee Engagement (Peak Hour)",
        ko: "티브레이크 제공 · 스타트업 쇼케이스 및 참가자 교류 (집중 네트워킹 시간)",
        recs: ["SHBC 참가자 및 잠재 파트너와 집중 네트워킹 권장"] },
      { start: "11:30", end: "13:00", type: "ops",
        title: "Startup Showcase & Business Networking (Off Peak)",
        ko: "스타트업 쇼케이스 및 비즈니스 네트워킹 (비집중 시간)",
        recs: ["필요 기업 대상 AV 체크 및 리허설 예정"],
        parallel: [
          { title: "Track 1A: Adding Years to Life – Why Value-Based Care Matters", ko: "건강수명 연장 – 가치 기반 의료가 중요한 이유", rec: "관심 분야에 따라 선택 참석 권장" },
          { title: "Track 1B: AI in Clinical Care in 2026: Friend or Foe", ko: "2026년 임상현장의 AI: 친구인가, 적인가", rec: "AI·디지털헬스 기업 참석 권장" },
          { title: "Track 1C: A Responsible Future: Navigating the Ethics of Predictive and Preventive Medicine", ko: "책임 있는 미래: 예측·예방의학의 윤리적 과제", rec: "예방·예측의료 관련 기업 선택 참석 권장" },
        ] },
      { start: "13:00", end: "14:30", type: "network",
        title: "Lunch (provided) · Startup Showcase & Attendee Engagement (Peak Hour)",
        ko: "중식 제공 · 스타트업 쇼케이스 및 참가자 교류 (집중 네트워킹 시간)",
        recs: ["참가자 및 파트너와 적극적인 네트워킹 권장"] },
      { start: "14:30", end: "16:00", type: "key", pitch: true,
        title: "CONNECT 2026 · Pitchstop",
        ko: "스타트업 전용 피칭 세션 · 기업별 5분 발표 + 5분 Q&A",
        recs: ["CONNECT 2026 key programme", "Investor 및 헬스케어 혁신 관계자 대상 기업 소개", "투자/사업화 피드백·PoC·사업협력 기회 발굴 예정"] },
      { start: "16:00", end: "16:30", type: "network",
        title: "Tea Break (provided) · Startup Showcase & Attendee Engagement (Peak Hour)",
        ko: "티브레이크 제공 · 스타트업 쇼케이스 및 참가자 교류 (집중 네트워킹 시간)",
        recs: ["Pitchstop 관심 파트너 대상 후속 네트워킹 권장"] },
      { start: "16:30", end: "18:00", type: "session",
        title: "Track 2A: Innovation for Healthy Longevity – From Bench to Clinic (Hall 1)",
        ko: "건강한 장수를 위한 혁신 – 연구실에서 임상으로 (Hall 1)",
        recs: ["CMTi-supported session", "기초연구 → 임상혁신 전환과정 이해", "임상·산업 협력 가능성 발굴", "관련 스타트업 참석 권장"] },
    ],
  },
  "2026-10-09": {
    label: "9 October",
    ko: "10월 9일 (금)",
    slots: [
      { start: "08:30", end: "08:45", type: "ops",
        title: "Booth Readiness Check – No re-setup required",
        ko: "부스 준비상태 확인 – 별도 재설치 불필요",
        recs: ["전시 시작 전 기업별 카운터 최종 점검 예정"] },
      { start: "08:45", end: "10:30", type: "ops",
        title: "Startup Showcase & Business Networking (Off Peak)",
        ko: "스타트업 쇼케이스 및 비즈니스 네트워킹 (비집중 시간)",
        recs: ["자유 비즈니스 네트워킹 및 전시 운영"],
        parallel: [
          { title: "Plenary 3: Singapore’s National Precision Medicine Programme: Translating Genomics into Research, Innovation and Enterprise Impact", ko: "싱가포르 국가 정밀의료 프로그램 – 유전체 연구를 연구·혁신·산업적 성과로 연결", rec: "정밀의료·유전체 분야 관련 기업 참석 권장 · 싱가포르 헬스케어 혁신 생태계 이해" },
          { title: "Panel Discussion: Singapore’s Precision Medicine Journey – From Genomic Discovery to Healthcare Impact", ko: "싱가포르 정밀의료의 여정 – 유전체 발견에서 헬스케어 임팩트까지", rec: "임상 적용 및 사업화 관점 참고 권장" },
        ] },
      { start: "10:30", end: "11:00", type: "network",
        title: "Tea Break (provided) · Startup Showcase & Attendee Engagement (Peak Hour)",
        ko: "티브레이크 제공 · 스타트업 쇼케이스 및 참가자 교류 (집중 네트워킹 시간)",
        recs: ["핵심 네트워킹 시간", "참가자 및 잠재 파트너와의 집중 네트워킹 권장"] },
      { start: "11:00", end: "12:30", type: "ops",
        title: "Startup Showcase & Business Networking (Off Peak)",
        ko: "스타트업 쇼케이스 및 비즈니스 네트워킹 (비집중 시간)",
        recs: ["정밀의료 관련 기업 참석 권장"],
        parallel: [
          { title: "3A Precision Medicine in Shaping the Future of Healthcare Delivery in Singapore", ko: "싱가포르 의료서비스의 미래를 이끄는 정밀의료", rec: "근골격·재활·헬스케어 관련 기업 선택 참석 권장" },
          { title: "3B Frontiers in Muscle Health", ko: "근육 건강의 새로운 프런티어", rec: "관련 기업 선택 참석 권장" },
          { title: "3C All Hands on Deck: Building a Generalist Palliative Care Ecosystem", ko: "모두가 함께 만드는 일반 완화의료 생태계", rec: "핵심 비즈니스 네트워킹 시간" },
        ] },
      { start: "12:30", end: "14:00", type: "network",
        title: "Lunch (provided) · Startup Showcase & Attendee Engagement (Peak Hour)",
        ko: "중식 제공 · 스타트업 쇼케이스 및 참가자 교류 (집중 네트워킹 시간)",
        recs: ["기존 미팅 상대 및 신규 파트너와의 후속 논의 권장"] },
      { start: "14:00", end: "15:30", type: "ops",
        title: "Startup Showcase & Business Networking (Off Peak)",
        ko: "스타트업 쇼케이스 및 비즈니스 네트워킹 (비집중 시간)",
        recs: ["자유 비즈니스 네트워킹 및 전시 운영"],
        parallel: [
          { title: "Plenary 4: A Social Norms Approach to Healthy Living: How Theory Informs Practice and Practice Theory – Prof. Rajiv N. Rimal", ko: "건강한 삶을 위한 사회규범 접근법: 이론과 실천의 상호작용 – Prof. Rajiv N. Rimal", rec: "예방·건강증진 관련 기업 참석 권장" },
        ] },
      { start: "15:30", end: "16:00", type: "network",
        title: "Tea Break (provided) · Startup Showcase & Attendee Engagement (Peak Hour)",
        ko: "티브레이크 제공 · 스타트업 쇼케이스 및 참가자 교류 (집중 네트워킹 시간)",
        recs: ["행사 종료 전 최종 네트워킹 시간", "주요 파트너 대상 최종 네트워킹 및 후속 논의 권장"] },
      { start: "16:00", end: "17:30", type: "ops",
        title: "Close & Counter Wrap-up – Final follow-ups; startup counters to close by 17:00",
        ko: "마감 및 카운터 정리 – 최종 후속 미팅 진행 및 17:00까지 스타트업 카운터 운영 종료",
        recs: ["주요 파트너 대상 최종 후속 논의 권장", "17:00 기업 카운터 운영 종료 예정"],
        parallel: [
          { title: "4A Digital Health: Bridging the Tech Divide", ko: "디지털 헬스 – 기술 격차를 연결하다", rec: "디지털헬스 기업 참석 권장" },
          { title: "4B Extending Healthspan by Design: Clinical 3D Printing across the Care Continuum", ko: "디자인으로 확장하는 건강수명 – 의료 전주기의 임상 3D 프린팅", rec: "메드테크·3D 프린팅 관련 기업 선택 참석 권장" },
          { title: "4C Golden Resilience – Empowering and Supporting Our Elderly Patients in Their Cancer Journey", ko: "Golden Resilience – 고령 암환자의 치료 여정을 지원하고 역량을 강화하기", rec: "항암·건강노화 관련 기업 참석 권장" },
        ] },
    ],
  },
};

/* 기업 브로슈어 — null 값은 "업데이트 예정"으로 표시됩니다.
   achievements · expansion 은 문장 하나(string) 또는 항목 목록(array) 모두 가능합니다.
   관리 시트 A열(로그인 ID)이 id 또는 aliases 중 하나와 같으면 이 기업으로 인식합니다. (대소문자 무관) */
window.COMPANIES = [
  { id: "speechnrt", aliases: ["speech", "speech nrt"], no: 1, pitch: "14:30",
    name: "Speech NRT Co.", legal: "MalGwaHakNoRiTeo Co.", tagline: null,
    summary: "AI-powered personalized speech rehabilitation platform combining speech analysis, pronunciation training, and digital therapeutics.",
    tags: ["Digital Health", "DTx", "AI"],
    rep: null, founded: null, location: null,
    core: null, achievements: null, expansion: null,
    website: null, email: null, contactPerson: null },
  { id: "lifefuturetech", aliases: [], no: 2, pitch: "14:40",
    name: "Lifefuturetech", legal: null, tagline: null,
    summary: "AI-powered healthcare platform delivering personalized health monitoring, clinical communication, and end-to-end medical support through Med-LLM technology.",
    tags: ["Digital Health", "Med-LLM"],
    rep: null, founded: null, location: null,
    core: null, achievements: null, expansion: null,
    website: null, email: null, contactPerson: null },
  { id: "cdthera", aliases: ["cd thera"], no: 3, pitch: "14:50",
    name: "CDThera Inc.", legal: null, tagline: "Non-invasive saliva-based AI dementia risk screening",
    summary: "Early Detection, Better Prevention — a non-invasive oral-saliva multi-biomarker + AI platform (PDX-AD) for early, at-home dementia risk screening and longitudinal brain-health monitoring.",
    tags: ["Digital Health", "Saliva Biomarker", "AI Diagnostics"],
    rep: "Do-Hye Kwon (CEO & Co-Founder)", founded: null, location: "Korea",
    core: "Early Detection, Better Prevention — a non-invasive oral-saliva multi-biomarker + AI platform (PDX-AD) for early, at-home dementia risk screening and longitudinal brain-health monitoring. The PDX-AD saliva test kit analyzes dementia-related biomarkers (Aβ42/40, p-Tau; Advanced adds BDNF and Calprotectin) and turns them into a personalized 0–100 dementia risk score with monitoring reports, while the AI risk assessment platform classifies risk tiers and forecasts 3–5 year onset risk.",
    achievements: [
      "Saliva biomarkers cross-validated against blood (n=127 paired samples; Aβ42/40 R²=0.8104, p-Tau R²=0.8470, p<0.001), enabling repeatable at-home screening years before symptom onset",
      "AI risk-prediction model: internal AUC 0.882 (n=53 high-risk cohort), externally validated on two independent cohorts (AUC 0.847 and 0.835)",
      "Lead candidate PDX-AD has reached general-population screening/diagnostic-testing readiness; Basic and Advanced test kits planned for commercial launch in 2026",
      "Academic and clinical partners include Kinexus Bioinformatics, Johns Hopkins University, Korea Electronics Technology Institute and Seoul National University Hospital",
    ],
    expansion: [
      "Scaling from a Korea-first dementia-screening platform toward a multi-disease ‘Brain & Precision Healthcare’ platform, with Singapore as the priority beachhead for ASEAN expansion",
      "Channel expansion from direct-to-consumer into hospitals, nursing facilities, health-checkup centers, wellness programs and insurance/corporate-welfare partners",
      "Platform reuse for cardiovascular disease and hematologic malignancies on the same saliva-sample and AI-engine infrastructure",
    ],
    website: null, email: null, contactPerson: null },
  { id: "careminder", aliases: [], no: 4, pitch: "15:00",
    name: "CareMinder Co., Ltd.", legal: null, tagline: "Medical voice-AI automating nursing documentation",
    summary: "CareFlow — a medical voice-recognition AI suite (CareVoice · CareLink · CareForm · CareNote) automating nursing and care documentation.",
    tags: ["Medical AI", "Voice AI", "Digital Health"],
    rep: "Joongu Kang (CEO) · Yujin Lee (CSO)", founded: "Aug 2024", location: "Seoul, Korea",
    core: "CareFlow — a medical voice-recognition AI suite (CareVoice · CareLink · CareForm · CareNote) automating nursing and care documentation. CareNote auto-charts nurse–patient voice conversations into SOAP/PASS-BAR nursing formats with encrypted transmission and immediate deletion (ISO 27001-based); CareLink lets patients send nursing requests by voice or button from a mobile app or wall-mounted tablet; a multilingual AI engine feeds a real-time per-bed request dashboard that integrates with groupware (Naver Works, Slack, MS Teams).",
    achievements: [
      "Best-in-class medical speech accuracy: CER 0.0997 — up to ~4.8x lower error rate than competing medical speech recognition, clinically validated in an IRB-approved study at SNU Bundang Hospital (Apr 2026)",
      "Demonstrated 39-minute reduction in nurse shift-handover preparation time",
      "CareLink reduces unnecessary nurse calls by approximately 46%",
      "8+ hospital network (Samsung Seoul, Korea Univ. Guro, Ajou, etc.); SK Telecom technology-transfer MOU (Oct 2025); selected for KB Financial Group’s KB Starters program (2025) and the Naver D2SF Campus program",
    ],
    expansion: [
      "Global conference presence: MWC Barcelona (Mar 2025), Singapore SWITCH (Oct 2025) and CES Las Vegas (Jan 2026); Hong Kong entity established via HKSTP (Feb 2026)",
      "Three revenue lines: B2B nursing-hospital subscription through Donggu Bio Pharm’s sales channel, B2B2C family/guardian care reports, and a B2C nurse voice-charting app",
      "Nursing-influencer and community marketing to build a nurse user base",
    ],
    website: null, email: null, contactPerson: null },
  { id: "jeongjin", aliases: ["jeongjin bioscience"], no: 5, pitch: "15:10",
    name: "JEONGJIN BIOSCIENCE Co., Ltd.", legal: null, tagline: "Cell-free secretome therapeutics for inflammatory disease",
    summary: "A cell-free therapeutics company maximizing the potential of cell-derived secretome to develop fundamental treatments and functional ingredients for intractable inflammatory disease.",
    tags: ["Cell-free Therapeutics", "Secretome", "Inflammatory Disease"],
    rep: "Chin Hee Mun, Ph.D. (CEO) · Jae Hwan Kim, Ph.D. (CSO)", founded: "Jan 2023", location: "Seoul, Korea",
    core: "A cell-free therapeutics company maximizing the potential of cell-derived secretome to develop fundamental treatments and functional ingredients for intractable inflammatory disease. iSecretome 2.0 (JJ-11) is a UC-MSC-derived cell-free secretome for ulcerative colitis/IBD that converts inflammatory T-cells and macrophages to anti-inflammatory phenotypes while inducing intestinal epithelial regeneration; oSecretome 1.0 (JJ-31) is an NK-cell secretome-based anticancer candidate for solid tumors, with non-small-cell lung cancer as the priority indication.",
    achievements: [
      "Dual-target cell-free platform: over 30% better anti-inflammatory efficacy than non-responders to sulfasalazine and anti-TNF-α antibodies in preclinical models",
      "JJ-31: 37–49% tumor-weight reduction in preclinical animal models — comparable to or better than standard-of-care paclitaxel — with 80–90% cancer-cell killing in vitro",
      "JJ-11: non-GLP in-vivo safety and efficacy validated; GLP preclinical studies in progress; KFDA IND submission targeted for Q2 2027",
      "Cell-free ‘function-only delivery’ avoids structural risks of live-cell administration; lyophilized formulation enables long-term room-temperature/refrigerated storage",
      "FDA cell and gene therapy reviewer pre-meeting (2024); selected for TIPS and Ministry of Trade, Industry and Energy R&D programs",
    ],
    expansion: [
      "Staged global licensing (license-out) of JJ-11 and JJ-31, targeting big-pharma partners such as Takeda, AbbVie and Janssen",
      "B2B exclusive supply of a high-value API ingredient (minimum 30L/month) for skin-booster and functional cosmetics, followed by an in-house private-label brand",
      "Global KOL and institutional networking with UCSF, Stanford, Monash University and CCRM; overseas clinical CRO network including Linkorus (U.S.), Flann (San Francisco Regenerative Association) and Nucleus Network (Australia)",
    ],
    website: null, email: null, contactPerson: null },
  { id: "beyondmedicine", aliases: ["beyond", "beyond medicine"], no: 6, pitch: "15:20",
    name: "Beyond Medicine", legal: null, tagline: "Prescription Digital Therapeutic for Temporomandibular Disorders",
    summary: "Clickless — a prescription digital therapeutic (DTx/SaMD) delivering a 6-week structured program for temporomandibular disorder (TMD) treatment.",
    tags: ["Digital Health", "DTx / SaMD", "TMD"],
    rep: "Daehyun Kim, DDS, PhD (CEO & Founder)", founded: null, location: null,
    core: "Clickless — a prescription digital therapeutic (DTx/SaMD) delivering a 6-week structured program for temporomandibular disorder (TMD) treatment. Clickless (TMD-01) combines guided jaw exercises, oral-behavior awareness and modification, TMD education, relaxation and psychoeducational content, pain/symptom monitoring and data-driven feedback, paired with a clinician dashboard for prescription and remote adherence monitoring.",
    achievements: [
      "MFDS Class II SaMD approval in Korea (Dec 2025); initial commercial prescribing launched in 2026",
      "Published 102-patient multicenter, double-blind, randomized, sham-controlled RCT (JMIR, Oct 2025): greater pain reduction and significant improvements in maximum mouth opening, jaw function and oral behaviors versus sham at 6 weeks",
      "MFDS Innovative Medical Device designation (No. 82, Dec 2024); selected for TIPS (Dec 2025)",
      "Top Excellence Award, 2nd Shin Kyuk-ho Lotte Young Entrepreneur Awards (Dec 2025); selected for Korea’s Innovation Premier 1000 (Aug 2026)",
      "U.S. FDA CDRH acknowledgement received for Pre-Submission (Jul 2026)",
    ],
    expansion: [
      "Singapore as the regional clinical and commercial reference market, followed by selective ASEAN expansion — then the US and Europe as regulatory programs advance",
      "U.S.: incorporating FDA Pre-Submission feedback toward a marketing submission (510(k) or De Novo) targeted for 2027; EU CE-MDR readiness and Singapore HSA market-entry planning underway",
      "Working with qualified local distributors and commercialization partners for regulatory support, market access, and hospital and dental-clinic sales; selecting a Singapore regulatory and commercialization partner",
    ],
    website: null, email: null, contactPerson: null },
  { id: "inexoplat", aliases: [], no: 7, pitch: "15:30",
    name: "INEXOPLAT, Inc.", legal: null, tagline: "Dual-value translational immuno-oncology platform",
    summary: "A translational immuno-oncology company developing innate immune TME reprogramming therapies for difficult-to-treat solid tumors, with companion-animal clinical development providing both near-term commercial value and a translational bridge to human oncology.",
    tags: ["Immuno-Oncology", "Veterinary Oncology", "Extracellular Vesicles"],
    rep: "Sunghwan Kim (CEO) · Jungmin Lee (CSO)", founded: "Mar 2021", location: "Pohang / Incheon, Korea",
    core: "Dual-Value Translational Immuno-Oncology Platform — a translational immuno-oncology company developing innate immune TME reprogramming therapies for difficult-to-treat solid tumors, with companion-animal clinical development providing both near-term commercial value and a translational bridge to human oncology. IEP-01V is an EV-based innate immune-modulating therapy for dogs and cats with advanced solid tumors; IEP-01 is its human counterpart, with pancreatic cancer as the lead indication. Both share a common innate-immune mechanism and a scalable EV manufacturing platform.",
    achievements: [
      "IEP-01 is designed to activate innate immunity through DC/macrophage modulation and reprogram an immunosuppressive ‘cold’ TME toward an immune-active state; multi-tumor preclinical data support development in difficult-to-treat solid tumors",
      "IEP-01V: preclinical efficacy and preliminary safety package established; prospective canine Phase 1/pilot and immune-biomarker study planned for 2027",
      "IEP-01: human-relevant translational validation, ex-vivo tumor/immune studies and IND-enabling pharmacology; IND filing / FIH preparation planned for 2028–2029",
      "Selected for BiiG WAVE, Shinhan Square Bridge Incheon and the TIPS program (2023); 4th Daewoong Group INNOBEAR Open Innovation Program and K-Bio LabHub member company (2025)",
    ],
    expansion: [
      "Dual-track comparative-oncology strategy: veterinary partnering and co-development/licensing with veterinary oncology centers and global Animal Health companies (IEP-01V), then pharma co-development and licensing for human IEP-01",
      "Prospective companion-animal clinical studies across Korea, Singapore and APAC, building a partner-ready evidence package (veterinary outcomes, safety/immune-biomarker data, CMC readiness)",
      "Engaging clinician-scientists, translational oncology researchers, veterinary KOLs, Animal Health companies, human oncology partners and investors across Singapore/APAC",
    ],
    website: null, email: null, contactPerson: null },
  { id: "imitarscience", aliases: ["imitar", "imita", "imita science"], no: 8, pitch: "15:40",
    name: "IMITAR SCIENCE Inc.", legal: null, tagline: "Organ-on-a-chip platform for metabolic disease R&D",
    summary: "A world without animal testing — a human-like multi-organ-on-a-chip (MSoC) platform resolving the preclinical bottleneck in metabolic-disease drug development.",
    tags: ["Organ-on-a-chip", "Non-clinical CRO", "Metabolic Disease"],
    rep: "Cheolmin Tae, M.D. · Geumgyu Park (Co-CEOs)", founded: "Jul 2021", location: "Incheon, Korea",
    core: "A world without animal testing — a human-like multi-organ-on-a-chip (MSoC) platform resolving the preclinical bottleneck in metabolic-disease drug development. MSoC (Metabolic System on Chip) is a postage-stamp-sized chip co-culturing organ organoids (gut, liver, kidney, fat, skin) via pump-free microchannels connected by vascular/immune-cell networks to replicate human-like ADME metabolism; up to 2–4 organs can be linked. MSoC Flow™ / Gravity Machine provides automated pump-free fluid flow, and the 3-in-1 automation equipment adds AI-based organoid differentiation, culture and drug-efficacy evaluation.",
    achievements: [
      "Korea’s only 2–4 organ metabolic MSoC platform — long-term metabolic connectivity on a single chip, with pump-free fluid flow usable without specialized operating personnel",
      "Real-use references: a Ministry of Health & Welfare national project (with Toolgen and KIST; obesity/diabetes 4-organ model), a fatty-liver (gut–liver) model supplied to Huons, and MOUs with Ewha Womans University Mokdong Hospital and SNU Bundang Hospital",
      "Apr 2026: MSoC chip sale to Samyang Foods; May 2024: selected for the startup ‘stepping stone’ R&D program",
    ],
    expansion: [
      "Aims to become the definitive preclinical evaluation platform for advanced biopharmaceuticals (ATMPs) as the industry shifts toward New Approach Methodologies",
      "CRO services for pharma and hospital researchers (toxicity/metabolic evaluation, custom experiments), plus technology licensing of the MSoC platform to CRO and medical-device companies",
      "Target linkage to 2028 MFDS approval and the FDA Modernization Act 2.0 pathway",
    ],
    website: null, email: null, contactPerson: null },
];
